set_property SRC_FILE_INFO {cfile:C:/Users/jgpei/ebaz_hello_world/ebaz_hello_world.srcs/constrs_1/new/ppp.xdc rfile:../../../ebaz_hello_world.srcs/constrs_1/new/ppp.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H16 [get_ports UART0_RX_0]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H17 [get_ports UART0_TX_0]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E19 [get_ports {pwm_out_0_tri_o[0]}]
